version: "3.8"
services:
  latex-base:
    build:
      context: ./base
      network: host
      args:
        BASE_IMAGE: ubuntu:22.04
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
        TEXLIVE_VERSION: ${TEXLIVE_VERSION}
        TEXLIVE_SCHEME: ${TEXLIVE_SCHEME}
        GIRARA_VERSION: ${GIRARA_VERSION}
        ZATHURA_VERSION: ${ZATHURA_VERSION}
        MUPDF_VERSION: ${MUPDF_VERSION}
        ZATHURA_PDF_MUPDF_VERSION: ${ZATHURA_PDF_MUPDF_VERSION}
    image: texlive${TEXLIVE_VERSION}-${TEXLIVE_SCHEME}:base
  latex-dev:
    build:
      network: host
      args:
        BASE_IMAGE: texlive${TEXLIVE_VERSION}-${TEXLIVE_SCHEME}:base
        http_proxy: ${http_proxy}
        HTTP_PROXY: ${HTTP_PROXY}
        https_proxy: ${https_proxy}
        HTTPS_PROXY: ${HTTPS_PROXY}
        USER: ${USER}
        UID: ${UID}
        GID: ${GID}
        HOME: ${HOME}
        NEOVIM_VERSION: ${NEOVIM_VERSION}
        TEXLAB_VERSION: ${TEXLAB_VERSION}
        TMUX_VERSION: ${TMUX_VERSION}
        DISPLAY: ${DISPLAY}
    image: texlive${TEXLIVE_VERSION}-${TEXLIVE_SCHEME}:dev
    container_name: latex_dev
    stdin_open: true
    tty: true
    network_mode: host
    user: ${UID}:${GID}
    volumes:
      # x11 socket
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # dbus socket
      - /run/user/${UID}/at-spi:/run/user/${UID}/at-spi:rw
      # nvim configuration
      - ~/.config/nvim/:${HOME}/.config/nvim/:ro
      # tmux configuration
      - ~/.tmux.conf:${HOME}/.tmux.conf:ro
      # workspace
      - ~/notes/:${HOME}/notes/:rw
      - ~/dev/resume/:${HOME}/resume/:rw
      - ~/dev/notes/:${HOME}/dev/notes/:rw
    env_file: ./.env
    restart: always
