version: "3.8"
services:
  latex:
    image: latex:dev
    container_name: latex
    env_file: ./.env
    user: ${DOCKER_UID}:${DOCKER_GID}
    network_mode: ${NETWORK_MODE}
    stdin_open: true
    tty: true
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      network: ${NETWORK_MODE}
      args:
        DOCKER_BUILDKIT: ${DOCKER_BUILDKIT}
        BASE_IMAGE: ${BASE_IMAGE}
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        TEXLIVE_VERSION: ${TEXLIVE_VERSION}
        TEXLIVE_SCHEME: ${TEXLIVE_SCHEME}
        GIRARA_VERSION: ${GIRARA_VERSION}
        ZATHURA_VERSION: ${ZATHURA_VERSION}
        MUPDF_VERSION: ${MUPDF_VERSION}
        ZATHURA_PDF_MUPDF_VERSION: ${ZATHURA_PDF_MUPDF_VERSION}
        NEOVIM_VERSION: ${NEOVIM_VERSION}
        TMUX_VERSION: ${TMUX_VERSION}
        DOCKER_USER: ${DOCKER_USER}
        DOCKER_HOME: ${DOCKER_HOME}
        DOCKER_UID: ${DOCKER_UID}
        DOCKER_GID: ${DOCKER_GID}
    volumes:
      # x11 socket
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # dbus socket
      - /run/user/${DOCKER_UID}/at-spi:/run/user/${DOCKER_UID}/at-spi:rw
      # nvim configuration
      - ~/.config/nvim/:${DOCKER_HOME}/.config/nvim/:ro
      # tmux configuration
      - ~/.config/tmux/tmux.conf:${DOCKER_HOME}//.config/tmux/tmux.conf:ro
      # zsh configuration
      - ~/.zshrc:${DOCKER_HOME}/.zshrc:ro
      - ~/.oh-my-zsh/custom/:${DOCKER_HOME}/.oh-my-zsh/custom/:ro
      # starship configuration
      - ~/.config/starship.toml:${DOCKER_HOME}/.config/starship.toml:ro
      # zathura configuration
      - ~/.config/zathura/:${DOCKER_HOME}/.config/zathura/:ro
      # workspaces
      - ~/dev/resume/:${DOCKER_HOME}/dev/resume/:rw
      - ~/dev/notes/:${DOCKER_HOME}/dev/notes/:rw
