services:
  latex:
    build:
      args:
        BASE_IMAGE: ${BASE_IMAGE}
        BUILDTIME_NETWORK_MODE: ${BUILDTIME_NETWORK_MODE}
        COMPILE_JOBS: ${COMPILE_JOBS}
        DOCKER_BUILDKIT: ${DOCKER_BUILDKIT}
        DOCKER_GID: ${DOCKER_GID}
        DOCKER_HOME: ${DOCKER_HOME}
        DOCKER_UID: ${DOCKER_UID}
        DOCKER_USER: ${DOCKER_USER}
        NEOVIM_VERSION: ${NEOVIM_VERSION}
        SETUP_FLAG: ${SETUP_FLAG}
        SSH_PORT: ${SSH_PORT}
        TEXLIVE_SCHEME: ${TEXLIVE_SCHEME}
        TEXLIVE_VERSION: ${TEXLIVE_VERSION}
        TMUX_GIT_REFERENCE: ${TMUX_GIT_REFERENCE}
        ZSH_VERSION: ${ZSH_VERSION}
      context: .
      dockerfile: Dockerfile
      network: ${BUILDTIME_NETWORK_MODE}
    command:
    - zsh
    - -i
    container_name: latex
    deploy:
      resources:
        limits:
          cpus: 14.0
          memory: 15.49G
        reservations:
          cpus: 1.75
          devices:
          - capabilities:
            - gpu
            count: all
            driver: nvidia
          memory: 1.94G
    entrypoint:
    - zsh
    - -i
    - /entrypoint.sh
    env_file: .env
    extra_hosts:
    - host.docker.internal:host-gateway
    image: latex:latest
    ipc: host
    network_mode: ${RUNTIME_NETWORK_MODE}
    privileged: true
    restart: always
    runtime: nvidia
    stdin_open: true
    tty: true
    user: ${DOCKER_UID}:${DOCKER_GID}
    volumes:
    - ~/Projects:${DOCKER_HOME}/Projects:rw
    - ~/Documents:${DOCKER_HOME}/Documents:rw
    - ~/Datasets:${DOCKER_HOME}/Datasets:rw
    - ~/Pictures:${DOCKER_HOME}/Pictures:rw
    - ~/Videos:${DOCKER_HOME}/Videos:rw
    - ~/.ssh:${DOCKER_HOME}/.ssh:ro
    - /run/user/1000:/run/user/1000:rw
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - /run/user/1000/bus:/run/user/1000/bus:rw
    - ./entrypoint.sh:/entrypoint.sh:ro
    security_opt:
      - apparmor:unconfined
