services:
  latex:
    build:
      args:
        BASE_IMAGE: ${BASE_IMAGE}
        BUILDTIME_HTTPS_PROXY: ${BUILDTIME_HTTPS_PROXY}
        BUILDTIME_HTTP_PROXY: ${BUILDTIME_HTTP_PROXY}
        BUILDTIME_NETWORK_MODE: ${BUILDTIME_NETWORK_MODE}
        DOCKER_BUILDKIT: ${DOCKER_BUILDKIT}
        DOCKER_GID: ${DOCKER_GID}
        DOCKER_HOME: ${DOCKER_HOME}
        DOCKER_UID: ${DOCKER_UID}
        DOCKER_USER: ${DOCKER_USER}
        NEOVIM_VERSION: ${NEOVIM_VERSION}
        SETUP_TIMESTAMP: ${SETUP_TIMESTAMP}
        TEXLIVE_SCHEME: ${TEXLIVE_SCHEME}
        TEXLIVE_VERSION: ${TEXLIVE_VERSION}
        TMUX_GIT_HASH: ${TMUX_GIT_HASH}
        TO_BUILD_ZATHURA: ${TO_BUILD_ZATHURA}
        XDG_PREFIX_DIR: ${XDG_PREFIX_DIR}
        buildtime_http_proxy: ${buildtime_http_proxy}
        buildtime_https_proxy: ${buildtime_https_proxy}
      context: .
      dockerfile: Dockerfile
      network: ${BUILDTIME_NETWORK_MODE}
    container_name: latex
    env_file: ./.env
    extra_hosts:
    - host.docker.internal:host-gateway
    image: latex
    ipc: host
    network_mode: ${RUNTIME_NETWORK_MODE}
    privileged: true
    restart: always
    runtime: ${RUNTIME}
    stdin_open: true
    tty: true
    user: ${DOCKER_UID}:${DOCKER_GID}
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - /run/user/${DOCKER_UID}/at-spi:/run/user/${DOCKER_UID}/at-spi:rw
    - ~/Documents:${DOCKER_HOME}/Documents:rw
    - ~/Projects:${DOCKER_HOME}/Projects:rw
    - ~/Pictures:${DOCKER_HOME}/Pictures:rw
    - ~/Videos:${DOCKER_HOME}/Videos:rw
